### ISSUE TITLE
Awkward Harbor login flow: Take the password from stdin

### ISSUE THREAD

**Issue by Vad1mo** [goharbor/harbor-cli#10]
like the --password-stdin [flag in Docker login](https://docs.docker.com/engine/reference/commandline/login/) is beneficial for security as it allows the password to be provided via standard input, preventing it from being exposed in command-line history or logs, enhancing overall password protection practices.

It would make sense if the harbor-cli followed the same pattern.

- [ ] Accept the password from stdin

**Comment by ZiyanK** [comment]
Hello @Vad1mo . I would like to work on this issue.
