### ISSUE TITLE
Add Password Prompt to Login

### ISSUE THREAD

**Issue by AquaBearCo** [goharbor/harbor-cli#108]
Would be good if Login had the ability to prompt for a hidden password for security. 

example ideas:
harbor login demo.goharbor.io -u admin 
Password Prompt: **********

harbor login demo.goharbor.io -u admin --passwordprompt
Password Prompt: **********

**Comment by bupd** [comment]
Hi @AquaBearCo,

Thank you for your suggestion! There is already an issue for handling password login #10 . Fixing that issue will address your request for a hidden password prompt during login.
Thanks.

**Comment by HiRoaR2002** [comment]
@bupd I tried logging in but got the message this message:-
![Screenshot 2024-06-18 164158](https://github.com/goharbor/harbor-cli/assets/100119451/4abf8c24-dea5-40fd-9e40-02c060f0cc93)

**Comment by bupd** [comment]
Yes it's a known issue. And it will be fixed when adding the PR.

it's coming because you gave the server as `demo.goharbor.io` instead of `https://demo.goharbor.io` 
try with https it should work.

Thanks.

**Comment by HiRoaR2002** [comment]
I have successfully created a password prompt using "term" package of go, which can invoked using --passprompt command
like this:-
![Screenshot 2024-06-18 205912](https://github.com/goharbor/harbor-cli/assets/100119451/f34d7f17-f51d-45f3-bf42-188c009b68fc)
I have also added a "Logged In Successfully" message as before there were notification.

**Comment by HiRoaR2002** [comment]
@AquaBearCo please assign the issue to me so that i can push the changes in new branch

**Comment by bupd** [comment]
Consider closing this issue as Harbor-CLI now by default masks password.

![masked Input lgin](https://github.com/user-attachments/assets/ae58b29c-a006-48fd-8f4b-77940686d7a9)
