### ISSUE TITLE
Result Presentation in YAML, JSON and Table 

### ISSUE THREAD

**Issue by Vad1mo** [goharbor/harbor-cli#11]
Similar to kubectl we want users of the harbor-cli users to provide the same representations and output options.

YAML, JSON, Table.

Currently, only JSON output is supported:

```shell
 ./harbor get project testproject-832165132
{
  "Payload": {
    "chart_count": 0,
    "creation_time": "2024-02-05T14:58:53.974Z",
    "current_user_role_ids": null,
    "cve_allowlist": {
      "creation_time": "0001-01-01T00:00:00.000Z",
      "id": 21,
      "items": [],
      "project_id": 20,
      "update_time": "0001-01-01T00:00:00.000Z"
    },
    "metadata": {
      "public": "true"
    },
    "name": "testproject-832165132",
    "owner_id": 20,
    "owner_name": "koenc",
    "project_id": 20,
    "repo_count": 2,
    "update_time": "2024-02-05T14:58:53.974Z"
  }
}
```

- [ ] Support YAML, JSON and Table output
- [ ] Make Table output default 
- [ ] -o wide: This parameter allows us to display extra information (if needed, otherwise -o wide should have no effect)
- [ ] In doubt, follow kubectl approach 

### Bonus points

- [ ] --sort-by: This parameter allows us to sort the output based on the resource attribute we specify.

### Out of Scope 

- Support of JSONPath, or GO template.
- -f, --field-selector=<attributename>=<attributevalue>: This parameter allows us to filter the output using some resource attributes.

**Comment by bishal7679** [comment]
@Vad1mo Assign this issue to me!
Would like to give it a try
