### ISSUE TITLE
Implement docker publish support using dagger SDK

### ISSUE THREAD

**Issue by bishal7679** [goharbor/harbor-cli#124]
## [👉](https://emojipedia.org/backhand-index-pointing-right) Follow along [dagger flow]
- [ ] Build the Go binary using a builder container
- [ ] Create a minimal runtime container
- [ ] Publish the container image
- [ ] Also needs to sign the published image for good supply chain security
- [ ] Needs to run this docker publish flow on every pull request merge to the upstream

**Comment by EraKin575** [comment]
Hi, @bishal7679 ! Can I work on this? You can assign me this issue after I have submitted a PR on it

**Comment by EraKin575** [comment]
hi @bishal7679 ! I wish to work on this issue. Can you assign me this issue?

**Comment by bupd** [comment]
@EraKin575 We don't assign issues here. Feel free to open PR!

**Comment by EraKin575** [comment]
Thanks! I will start working on this!

**Comment by bishal7679** [comment]
Hello @EraKin575 FYI I am already working on it
