### ISSUE TITLE
LFX Mentorship - Term 03 - 2024 September - October

### ISSUE THREAD

**Issue by Vad1mo** [goharbor/harbor-cli#142]
The Habor CLI Project is again looking for a mentee for the Harbor CLI project. 

Timeline: https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2024/03-Sep-Nov

mentee applications open | Jul 31 - Aug 13 5:00 PM PDT

Harbor-CLI, adding new capabilities and workflows.
Fixing issue
Releasing next usable version
For more details, see the proposal for the summer term --> https://github.com/cncf/mentoring/blob/main/programs/lfx-mentorship/2024/02-Jun-Aug/project_ideas.md

**Comment by Sweetdevil144** [comment]
Hello @Vad1mo , I'd willing to contribute for this term. Can you explain what you exxpect by `fixing issues` and `adding capabilities` and `workflows`. Will it be limited to adding new features in the existing `harbor` repository ?

**Comment by Sweetdevil144** [comment]
Also, what are the necessary workflows that we would need if proceeded with? I have one in my mind : 
+ Implementing an auto testing workflow whenever a Pull Request is made in the repository.

**Comment by VeerChaurasia** [comment]
Hey @Vad1mo,I'm eager to contribute to this term. Could you please elaborate on the specific issues we will be working to fix?

**Comment by mani1911** [comment]
@Vad1mo I really a Go programmer and am really curious to work on this

**Comment by mani1911** [comment]
Hey can you give me any pre tests that I can finish?
