### ISSUE TITLE
Setup `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by Sweetdevil144** [goharbor/harbor-cli#143]
Subtasks : 
+ Instantiate a `CONTRIBUTING.md` file.
+ Discuss with team and add documentations for setting up `harbor-cli` locally for development.

**Comment by bishal7679** [comment]
@Sweetdevil144 Which setup you need in order to start contributing for harbor-cli ?
Doesn't current Readme seems enough for you ?

**Comment by Sweetdevil144** [comment]
@bishal7679 wouldn't it be more 'apt' to have a separate `doc` on how to setup the repository for developers and contributors. Having it mixed up with `readme` isn't recommended.
Also, I would appreciate a sense of politeness !!

**Comment by bishal7679** [comment]
> @bishal7679 wouldn't it be more 'apt' to have a separate `doc` on how to setup the repository for developers and contributors. Having it mixed up with `readme` isn't recommended. Although it you insist, I'll close my Issue.
> 
> Also, I would appreciate a sense of politeness !!

You could look into the opened PRs [here](https://github.com/goharbor/harbor-cli/pull/115) beforehand 
Though I asked you a simple question regarding the need, doesn't mean insisting on closing!
Really apologize if Asked anything wrong :)
