### ISSUE TITLE
Fix Github Actions

### ISSUE THREAD

**Issue by bupd** [goharbor/harbor-cli#197]
Github Actions fail on every PRs with the below errors.
https://github.com/goharbor/harbor-cli/actions/runs/10971891257/job/30467526514?pr=97

## Requirements:

1. Docker Publish Workflow: Update the [docker_publish_workflow](https://github.com/goharbor/harbor-cli/blob/main/.github/workflows/docker_publish.yml) to trigger only on tag creation or release events, preventing runs on PRs.
   
2. Remove Module Dependency: Eliminate the dependency on the module, as seen in [this section](https://github.com/goharbor/harbor-cli/blob/62c3945a773d405a4cc8bfa9bad11031b69c54dc/.github/workflows/pull-request.yml#L42C10-L42C58). It's an unnecessary overhead.

3. Add Build Check Workflow: To check if building binaries for multiple operating systems and architectures are working as expected.

4. Add Formatting Check on Lint Workflow: To maintain consistent formatting.

5. Dagger Flag Update: Replace `--directory-arg` with the `--source` flag in the workflow, and set it as the default using the latest Dagger version.

**Comment by tylerauerbeck** [comment]
@bupd I'll be interested to see if this is still an issue with #201 merged.

**Comment by bupd** [comment]
## To close this issue:

1. Docker Publish Workflow: Update the [docker_publish_workflow](https://github.com/goharbor/harbor-cli/blob/main/.github/workflows/docker_publish.yml) to trigger only on tag creation or release events, preventing runs on PRs.
   
2. Remove Module Dependency: Eliminate the dependency on the module, as seen in [this section](https://github.com/goharbor/harbor-cli/blob/62c3945a773d405a4cc8bfa9bad11031b69c54dc/.github/workflows/pull-request.yml#L42C10-L42C58). It's an unnecessary overhead.

3. Add Build Check Workflow: To check if building binaries for multiple operating systems and architectures are working as expected.

4. Add Formatting Check on Lint Workflow: To maintain consistent formatting.

5. Dagger Flag Update: Replace `--directory-arg` with the `--source` flag in the workflow, and set it as the default using the latest Dagger version.

While #201 addresses some issues and removes unneccessary autogenerated code, it doesn’t cover the above key points which are essential for completely closing this issue as completed.

**Comment by tylerauerbeck** [comment]
Alright, 1, 2 and 5 have been resolved and merged. Will take a look at 3 and 4 next.
