### ISSUE TITLE
Build and export Binaries wit Dagger

### ISSUE THREAD

**Issue by Vad1mo** [goharbor/harbor-cli#214]
We used to run 
```console
dagger call build export --path=./bin
```

to build and export the binaries locally, now the command is exporting a bin file (which looks like the tgz. container image)

As a developer, I would like to use Dagger to build binaries. 

To speed up local development, I would be nice to have a debug build for my native platform.

**Comment by JianMinTang** [comment]
Hi @Vad1mo and @bupd, I added `BuildDev` function to build the Go binary for the specified platform.

**Comment by Vad1mo** [comment]
@tylerauerbeck
