### ISSUE TITLE
Checks were not successfull

### ISSUE THREAD

**Issue by Althaf66** [goharbor/harbor-cli#218]
Test_Login_Success function in the login_test.go file causing error. 
Due to invalid username and password, this showing error.

https://github.com/goharbor/harbor-cli/actions/runs/11505725892/job/32028075503?pr=121

**Comment by Vad1mo** [comment]
please go ahead an create a new user in demo.goharbor.io and use that for testing. However we should spin up a harbor instance ourself instead of relying on external one for testing.
