### ISSUE TITLE
E2E Tests for Harbor CLI

### ISSUE THREAD

**Issue by amands98** [goharbor/harbor-cli#23]
End-to-end tests are essential for ensuring the quality of Harbor CLI features

### Implementation
1. We can use [ginkgo](https://github.com/onsi/ginkgo) + [gomega](https://github.com/onsi/gomega)
- adopting a Behavior-Driven Development (BDD) approach.
- proven effective in various CLI projects, such as [kubectl](https://github.com/kubernetes/kubectl).

2. Standard Go testing framework to test the functionality of a CLI tool. 

Using Ginkgo and BDD for Harbor CLI tests can add complexity. Sticking with standard Go testing if the project is simple. But for complex projects, Ginkgo offers clearer tests, better collaboration.

Note: If you have alternative suggestions for constructing end-to-end tests for Harbor, please feel free to share your thoughts below.

// @OrlinVasilev @Vad1mo

**Comment by amands98** [comment]
Using Ginkgo and BDD for Harbor CLI tests can add complexity. Sticking with standard Go testing if the project is simple. But for complex projects, Ginkgo offers clearer tests, better collaboration.

[ Updated the Description ]

**Comment by bishal7679** [comment]
Specifically for harbor-cli it'd be better to stick with standard go test IMO which will also be helpful for codecov integration

**Comment by EshaanAgg** [comment]
Hi! Is this project open for external contributors? Not exactly E2E, but I had noticed that the [credential store](https://github.com/goharbor/harbor-cli/blob/main/pkg/utils/credential_store.go) has no associated tests with it. I would love to try o add a test suite for the same.

**Comment by Vad1mo** [comment]
> Hi! Is this project open for external contributors? Not exactly E2E, but I had noticed that the [credential store](https://github.com/goharbor/harbor-cli/blob/main/pkg/utils/credential_store.go) has no associated tests with it. I would love to try o add a test suite for the same.

Sure go ahead!

**Comment by criticic** [comment]
I noticed there are no unit tests in this repo, can I go ahead and create a PR for the same?

**Comment by Vad1mo** [comment]
sure @criticic
