### ISSUE TITLE
The test username does not meet the username requirements

### ISSUE THREAD

**Issue by JianMinTang** [goharbor/harbor-cli#234]
the user requirements:
<img width="510" alt="image" src="https://github.com/user-attachments/assets/d9de165b-c54d-45d4-88a1-b900a4398ffa">
the ValidateUserName funtion 
<img width="434" alt="image" src="https://github.com/user-attachments/assets/55599dc3-a7f5-4d4c-96ba-9ccf259b21e8">
the username for testing:
<img width="603" alt="image" src="https://github.com/user-attachments/assets/958e745c-7381-47a7-a654-60b1ee66cdda">
We need to standardize these validation requirements, eg `harbor-cli` can't work on this `ValidationUserName` function. @Vad1mo @bupd

**Comment by Roaster05** [comment]
Hey @JianMinTang @Vad1mo @bupd, 

I would like to work on this issue. I am thinking of adding the following symbols to the username validation pattern:

- **Period (`.`)**: Allows separation of words for better readability and supports email-like usernames.
- **Underscore (`_`)**: Widely used to enhance clarity and readability without introducing ambiguity.
- **Hyphen (`-`)**: Links multiple words, improving visual structure while maintaining compatibility with URLs and CLI.

Additionally, I propose enforcing a rule that disallows consecutive symbols in usernames. Valid usernames will start and end with alphanumeric characters and may have symbols in between, ensuring that patterns like `abc--bacd` are rejected, while formats like `xyz.symbol.abc` are accepted.

**Comment by Vad1mo** [comment]
> Hey @JianMinTang @Vad1mo @bupd, 
> 
> 
> 
> I would like to work on this issue. I am thinking of adding the following symbols to the username validation pattern:
> 
> 
> 
> - **Period (`.`)**: Allows separation of words for better readability and supports email-like usernames.
> 
> - **Underscore (`_`)**: Widely used to enhance clarity and readability without introducing ambiguity.
> 
> - **Hyphen (`-`)**: Links multiple words, improving visual structure while maintaining compatibility with URLs and CLI.
> 
> 
> 
> Additionally, I propose enforcing a rule that disallows consecutive symbols in usernames. Valid usernames will start and end with alphanumeric characters and may have symbols in between, ensuring that patterns like `abc--bacd` are rejected, while formats like `xyz.symbol.abc` are accepted.
> 
> 

The rules on the CLI should simply match with the rules on Harbor Server side.

**Comment by Roaster05** [comment]
> > Hey @JianMinTang @Vad1mo @bupd,
> > I would like to work on this issue. I am thinking of adding the following symbols to the username validation pattern:
> > 
> > * **Period (`.`)**: Allows separation of words for better readability and supports email-like usernames.
> > * **Underscore (`_`)**: Widely used to enhance clarity and readability without introducing ambiguity.
> > * **Hyphen (`-`)**: Links multiple words, improving visual structure while maintaining compatibility with URLs and CLI.
> > 
> > Additionally, I propose enforcing a rule that disallows consecutive symbols in usernames. Valid usernames will start and end with alphanumeric characters and may have symbols in between, ensuring that patterns like `abc--bacd` are rejected, while formats like `xyz.symbol.abc` are accepted.
> 
> The rules on the CLI should simply match with the rules on Harbor Server side.

To align with this, the current server-side username validation logic uses a function to detect illegal characters. You can check the relevant code [here](https://github.com/goharbor/harbor/blob/9e55afbb9a124dbe47562d56769ad4e9f14cb5ed/src/server/v2.0/handler/user.go#L514-L518). It references an illegal character list in the constants file [here](https://github.com/goharbor/harbor/blob/9e55afbb9a124dbe47562d56769ad4e9f14cb5ed/src/common/const.go#L235-L236). We can implement a similar validation function to ensure consistency across the CLI and server.

**Comment by Vad1mo** [comment]
Exactly

**Comment by Roaster05** [comment]
@Vad1mo I have submitted a PR to address this issue. Could you please take a look at it? Thank you!
