### ISSUE TITLE
Force deletes non empty projects 

### ISSUE THREAD

**Issue by Vad1mo** [goharbor/harbor-cli#243]
Projects that have artifacts can be deleted before the artifact is deletes. 

It would be good to have an `--force` option on delete that will first delete the artifacts and then the project. 

![image](https://github.com/user-attachments/assets/baf62c60-ff42-47b9-ade6-d561482ff7d3)

**Comment by adwait-godbole** [comment]
Hi, @Vad1mo. I am new to Harbor. Can I take up this issue? (I can't seem to find any `good first issues` sadly :()

**Comment by Vad1mo** [comment]
Sure go ahead
