### ISSUE TITLE
Login fails to use schema automatically

### ISSUE THREAD

**Issue by Vad1mo** [goharbor/harbor-cli#38]
Log in into harbor should work without specifying a schema. 

```shell
./harbor login 8gears.container-registry.com
login failed, please check your credentials: Get "https://localhost/8gears.container-registry.com/users/current": dial tcp [::1]:443: connect: connection refused
``` 

The following combinations of commands should all work with schema, without schema, port number.

- [ ] ./harbor login http://8gears.container-registry.com -> http port 80
- [ ] ./harbor login http://8gears.container-registry.com:5000 -> http port 5000
- [ ] ./harbor login https://8gears.container-registry.com -> https port 443
- [ ] ./harbor login 8gears.container-registry.com -> assume it is https port 443
- [ ] ./harbor login 8gears.container-registry.com:8443 -> assume it is https port 8443

**Comment by amands98** [comment]
Got it

**Comment by Mehul-Kumar-27** [comment]
@amands98 , can I take this issue ? . As far as I have understood, when a user gives us a server address, we check if it's in our `config.yaml` file. If it is present, we use the credentials from there to log them in. If it's not there, we prompt the user to log in manually ?

**Comment by bupd** [comment]
closing in favor #297
