### ISSUE TITLE
CLI Documentation

### ISSUE THREAD

**Issue by Vad1mo** [goharbor/harbor-cli#49]
We need to create and build some sort of documentation regarding the CLI and its basic and advances usage. 
Ideally something that can used on the CLI but also in the online form in Markdown.

Goal would be to generate a markdown in e.g docs dir, this dir would then imported by https://github.com/goharbor/website and rendered on as a page on [goharbor.io/](https://goharbor.io/)

- [ ] Create CLI Documentation in Markdown 
- [ ] Create a PR for https://github.com/goharbor/website that will render the docs in the main website

**Comment by criticic** [comment]
For many command-line users, one of the most used documentation, is the software's `manpage`, we can use a library like go-md2man, to convert our markdown documentations to man format.

**Comment by bupd** [comment]
We can use `cobra/doc` to automate docs generation in markdown and man for cli.
