### ISSUE TITLE
New Commands for harbor 

### ISSUE THREAD

**Issue by amands98** [goharbor/harbor-cli#54]
We could use commands like 'start' to open the harbor dashboard in the browser, and also to run the harbor.

Checkout the diagram. 

![image](https://github.com/goharbor/harbor-cli/assets/136564604/da55027c-f41c-4550-871f-104ebde23855)

Note :
I am proposing these commands; however, they have not been accepted yet

**Comment by ayushrakesh** [comment]
Hello @amands98 Should I work on this?

**Comment by bupd** [comment]
I would suggest using the login command to switch between contexts and also offer option to create new login too.
