### ISSUE TITLE
Bug: newline added for inputs while login in bash

### ISSUE THREAD

**Issue by muaz-32** [goharbor/harbor-cli#65]
When using bash in Windows, a new line is added with the input when enter is pressed for the next input. As a result, an extra space character is added to the server URL. It happens for all the inputs probably. For example, the password is changed due to carriage return so the user is unable to log in. Without pressing enter, the user cannot move to the next input. So it would be better to trim the spaces of the inputs.

System: Windows 10
Terminal: Bash

**Comment by amands98** [comment]
Could you record the video or Screen shot and explain what the problem was?

**Comment by muaz-32** [comment]
> Could you record the video or Screen shot and explain what the problem was?


https://github.com/goharbor/harbor-cli/assets/96006730/218b4690-5629-47d0-be60-8b9656d92e32

In the video, you can see that in the beginning an extra space is added with the server URL. So when I trimmed the spaces, it was an authentication error because the password was carrying one extra character (carriage return).

I have updated the PR description.

**Comment by bupd** [comment]
This has been fixed.
