### ISSUE TITLE
CLI login command incorrectly handles server URL

### ISSUE THREAD

**Issue by bupd** [goharbor/harbor-cli#68]
## Description
The Harbor CLI tool's login command does not correctly handle the specified server URL, resulting in various errors and failed login attempts.

I attached video for the clear Explanation.

https://github.com/goharbor/harbor-cli/assets/89722848/92dc7a72-78dd-4d48-b1b7-c4086861170f

it should follow the schema as discussed here: #38

![cliIssues](https://github.com/goharbor/harbor-cli/assets/89722848/4eec738b-9ea0-487c-a42c-7a26a88eccff)

**Comment by bupd** [comment]
Can I work on this @Vad1mo

**Comment by bishal7679** [comment]
Hey @bupd FYI this issue has already an associated PR [#51](https://github.com/goharbor/harbor-cli/pull/51) which is solving this issue.

**Comment by bupd** [comment]
Yeah, I looked into #51 and have some recommendations for solving the issue let's colloborate and solve this.

**Comment by EraKin575** [comment]
@bupd is this issue still relevant?

**Comment by bupd** [comment]
closing #68 as completed via  #134
